export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_PUBLISHERS = "SET_PUBLISHERS";
export const ADD_PUBLISHER = "ADD_PUBLISHER";
export const CANCEL_ADD_PUBLISHER = "CANCEL_ADD_PUBLISHER";
export const EDITING_PUBLISHER = "EDITING_PUBLISHER";
export const CANCEL_EDIT_PUBLISHER = "CANCEL_EDIT_PUBLISHER";
export const CHANGE_NAME_PUBLISHER = "CHANGE_NAME_PUBLISHER";
export const UPDATE_PUBLISHER = "UPDATE_PUBLISHER";
export const DELETE_PUBLISHER = "DELETE_PUBLISHER";

export const SET_DISCOUNTS = "SET_DISCOUNTS";
export const ADD_DISCOUNT = "ADD_DISCOUNT";
export const CANCEL_ADD_DISCOUNT = "CANCEL_ADD_DISCOUNT";
export const EDITING_DISCOUNT = "EDITING_DISCOUNT";
export const CANCEL_EDIT_DISCOUNT = "CANCEL_EDIT_DISCOUNT";
export const CHANGE_PERCENT_DISCOUNT = "CHANGE_PERCENT_DISCOUNT";
export const CHANGE_PUBLISHER_DISCOUNT = "CHANGE_PUBLISHER_DISCOUNT";
export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT";
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";

export const SET_BOOKS = "SET_BOOKS";
export const ADD_BOOK = "ADD_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CANCEL_ADD_CATEGORY = "CANCEL_ADD_CATEGORY";
export const EDITING_CATEGORY = "EDITING_CATEGORY";
export const CANCEL_EDIT_CATEGORY = "CANCEL_EDIT_CATEGORY";
export const CHANGE_NAME_CATEGORY = "CHANGE_NAME_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// for shop
export const SET_CATEGORIES_BOOKS = "SET_CATEGORIES_BOOKS";